//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class product
    {
        public int Product_Id { get; set; }
        public string Product_name { get; set; }
        public string Product_Category { get; set; }
        public int Product_Price { get; set; }
        public int Product_Quantity { get; set; }
        public string Short_Description { get; set; }
        public string Long_Description { get; set; }
        public string Small_Image_path { get; set; }
        public string Large_Image_path { get; set; }

        public HttpPostedFileBase SImageFile { get; set; }

        public HttpPostedFileBase LImageFile { get; set; }


    }
}
